using System.Collections.Generic;
using Xamarin.Forms;

namespace VersionsInfo
{
    public class MockService : IService
    {
        private readonly List<Version> _versions;

        public MockService()
        {
            _versions = new List<Version>
            {
                new Version("1.5", "Cupcake","3","April 27, 2009", ImageSource.FromFile("Resources/drawable/cupcake.png"), "Android \"Cupcake\" (version 1.5) is a version of Android developed by Google, a major platform release deployable to Android-powered handsets starting in May 2009, that is no longer supported. The release includes new features for users and developers, as well as changes in the Android framework API. For developers, the Android 1.5 platform is available as a downloadable component for the Android SDK. Android 1.5 included new features such as an on-screen keyboard and Bluetooth support as well as improvements to existing features such as UI changes for application management and several Google apps."),
                new Version("1.6", "Donut","4", "September 15, 2009", ImageSource.FromFile("Resources/drawable/donut.png"), "Android \"Donut\" is a version of the open source Android mobile operating system developed by Google, that is no longer supported. Among the more prominent features introduced with this update were added support for CDMA smartphones, additional screen sizes, a battery usage indicator, and a text-to-speech engine. After the public release of Donut—its official dessert-themed code name the convention employed by Google to designate major Android versions—carriers were quick to follow with its roll out to customers in the form of an over-the-air(OTA) update for compatible smartphones."), 
                new Version("2.0 – 2.1", "Eclair", "5 – 7", "October 26, 2009", ImageSource.FromFile("Resources/drawable/eclair.png"), "Android 2.0 Eclair is Google’s 3rd big iteration of Android, not counting the 1.0 initial version. Android 1.5 Cupcake and Android 1.6 Donut came before Eclair. Android 2.0 Eclair actually brought some big steps forward for Android and started shaping up Google’s OS. Let’s check out the changes Google introduced with Android 2.0 Eclair. Expanded Account sync is definitely an important step forward, this feature allows you to add multiple accounts to a device for synchronization of e-mail and contact. Microsoft e-mail support was also added, with combined inbox to browse e-mail from multiple accounts in one page. Bluetooth technology is stepping forward as well, Android 2.1 support has been added by Google. Some neat shortcuts also found their way in this iteration of Android, like the ability to tap a Contacts photo and select whether you want to call, SMS or e-mail that person. You can now also search all saved SMS and MMS messages and set the OS to automatically delete oldest messages in a conversation when the defined limit is reached, which should help greatly with your memory. Google has also added a ton of new camera features, like flash support, digital zoom, scene mode, white balance, color effect and macro focus. The on-screen keyboard experience has also been improved, speed has been improved and the dictionary is now smarter than ever and learns from your word usage and includes contact names as suggestion. Browser UI has also been refreshed with bookmark thumbnails, double-tap zoom and support for HTML5.Calendar has been re - worked as well, it is now showing attending status for each invitee and the ability to invite new guests to events.Google has also optimized hardware speed and revamped the UI to some extent as well as added support for more screen sizes and resolutions with better contrast ratio.Google Maps also got an update to version 3.1.2 with tons of improvements.Live Wallpapers have also been added, animated wallpapers for those who prefer them are now available.Android 2.1 Eclair brought mainly bug fixes and stability improvements.That’s pretty much it, a long list indeed."), 
                new Version("2.2 – 2.2.3", "Froyo","8", "May 20, 2010", ImageSource.FromFile("Resources/drawable/froyo.png"), "Android 2.2 Froyo is Google’s 3rd big iteration of Android operating system. Google did its best to introduce some much-needed fixes to the OS and also introduce new features to it. Android 2.2 Froyo was introduced in May 2010. Google highlighted 4 areas from this update which you should know about, speed, APIs and services, browser and Android Market. As far as speed goes, Google introduced Dalvik JIT (Just In Time) compiler which deliver 2-5x performance boost to the CPU code compared to Android 2.1. Cloud to device messaging was introduced by Google in order to enable the developers to deliver a better experience when it comes to sync and notifications. Application backup API was also added here, welcome automatic restore function. Developers can now also specify if they want to allow users to install applications directly to SD cards or not. Wi-Fi portable hotspot is now here as well, if you’re on your mobile data connection and you want to give someone access to the internet via your phone, you can do that now via this function. Browser experience is significantly improved, with 2-3x faster javascript rendering. Android Market got “Update All” and “Auto Update” functions, which don’t need any further explanation I believe."), 
                new Version("2.3 – 2.3.7", "Gingerbread","9 – 10","December 6, 2010", ImageSource.FromFile("Resources/drawable/gingerbread.png"), "Android \"Gingerbread\" is a codename of the Android mobile operating system developed by Google and released in December 2010, for versions that are no longer supported. The Gingerbread release introduced support for near field communication (NFC)—used in mobile payment solutions—and Session Initiation Protocol (SIP)—used in VoIP internet telephony. Gingerbread's user interface was refined in many ways, making it easier to master, faster to use, and more power-efficient. A simplified color scheme with a black background gave vividness and contrast to the notification bar, menus, and other user interface components. Improvements in menus and settings resulted in easier navigation and system control. The Nexus S smartphone, released in 2010, was the first phone from the Google Nexus line that ran Gingerbread, and also the first one from the line with built-in NFC functionality. Gingerbread uses version 2.6.35 of the Linux kernel. As of 8 August 2017, statistics issued by Google indicate that 0.7% of all Android devices accessing Google Play run Gingerbread."), 
                new Version("3.0 – 3.2.6", "Honeycomb","11 – 13","February 22, 2011", ImageSource.FromFile("Resources/drawable/honeycomb.png"), "Android 3.0 Honeycomb is Google’s fifth update in a row, Android 1.6 Donut, 2.0 Eclair, 2.2 Froyo and 2.3 Gingerbread came before it. Honeycomb is a rather unique in a way though, this is a tablet only operating system and as far as Google tells us, it won’t be making its way to smartphones. One notable difference in Honeycomb is that there’s no longer a need for hardware buttons, they’re built into the OS itself. On the bottom left of the screen there are three software buttons: back, home and the app switcher button for multitasking (switching between running apps). On the bottom right you can find some addition info and functionality: power, internet connection status and a notification bar. Within the notification bar you can see download progress, music controls, incoming message profile pictures and so on. There are multiple widget options included with Honeycomb, so you can fill your homescreen with various widgets which will of course offer you all sorts of information and functionality. There’s of course your app drawer included here and tons of other functionality within the OS itself. Google really hopes Honeycomb will become a huge success and offer consumers new and functional way to use their tablets."), 
                new Version("4.0 – 4.0.4", "Ice Cream Sandwich","14 – 15","October 18, 2011", ImageSource.FromFile("Resources/drawable/IceCreamSandwich.png"), "Android 4.0–4.0.4 \"Ice Cream Sandwich\" is a version of the Android mobile operating system developed by Google. Unveiled on October 19, 2011, Android 4.0 builds upon the significant changes made by the tablet-only release Android Honeycomb, in an effort to create a unified platform for both smartphones and tablets. Android 4.0 was focused on simplifying and modernizing the overall Android experience around a new set of human interface guidelines. As part of these efforts, it introduced a new visual appearance codenamed \"Holo\", which is built around a cleaner, minimalist design, and a new default typeface named Roboto.It also introduced a number of other new features, including a refreshed home screen, near-field communication(NFC) support and the ability to \"beam\" content to another user using the technology, an updated web browser, a new contacts manager with social network integration, the ability to access the camera and control music playback from the lock screen, visual voicemail support, face recognition for device unlocking(\"Face Unlock\"), the ability to monitor and limit mobile data usage, and other internal improvements. Android 4.0 received positive reviews by critics, who praised the cleaner, revamped appearance of the operating system in comparison to previous versions, along with its improved performance and functionality.However, critics still felt that some of Android 4.0's stock apps were still lacking in quality and functionality in comparison to third-party equivalents, and regarded some of the operating system's new features, particularly the \"face unlock\" feature, as being gimmicks. As of 18 October 2017, statistics issued by Google indicate that 0.6% of all Android devices accessing Google Play run Ice Cream Sandwich."), 
                new Version("4.1 – 4.3.1", "Jelly Bean", "16 – 18","July 9, 2012",ImageSource.FromFile("Resources/drawable/jellyBean.png"), "Android \"Jelly Bean\" is the codename given to three major point releases of the Android mobile operating system developed by Google, spanning versions between 4.1 and 4.3.1, that are no longer supported. The first of these three, 4.1, was unveiled at Google's I/O developer conference in June 2012, focusing on performance improvements designed to give the operating system a smoother and more responsive feel, improvements to the notification system allowing for \"expandable\" notifications with action buttons, and other internal changes. Two more releases were made under the Jelly Bean name in October 2012 and July 2013 respectively, including 4.2—which included further optimizations, multi-user support for tablets, lock screen widgets, quick settings, and screen savers, and 4.3—contained further improvements and updates to the underlying Android platform. As of 8 August 2017, statistics issued by Google indicate that 7.6% of all Android devices accessing Google Play run Jelly Bean."), 
                new Version("4.4 – 4.4.4", "KitKat", "19 – 20","October 31, 2013",ImageSource.FromFile("Resources/drawable/kitKat.png"), "Android \"KitKat\" is a codename for the Android mobile operating system developed by Google, spanning versions between 4.4 and 4.4.4, that are no longer supported. Unveiled on September 3, 2013, KitKat focused primarily on optimizing the operating system for improved performance on entry-level devices with limited resources. As of November 2017, statistics issued by Google indicate that 13.8% of all Android devices accessing Google Play run KitKat."), 
                new Version("5.0 – 5.1.1", "Lollipop","21 – 22","November 12, 2014", ImageSource.FromFile("Resources/drawable/lollipop.png"), "Android \"Lollipop\" is a codename for the Android mobile operating system developed by Google, spanning versions between 5.0 and 5.1.1,[3] that is supported with security patches only.[4][5] Unveiled on June 25, 2014 at the Google I/O 2014 conference, it became available through official over-the-air (OTA) updates on November 12, 2014, for select devices that run distributions of Android serviced by Google (such as Nexus and Google Play edition devices). Its source code was made available on November 3, 2014. One of the most prominent changes in the Lollipop release is a redesigned user interface built around a design language known as Material Design, which was made to retain a paper-like feel to the interface. Other changes include improvements to the notifications, which can be accessed from the lockscreen and displayed within applications as top-of-the-screen banners.Google also made internal changes to the platform, with the Android Runtime(ART) officially replacing Dalvik for improved application performance, and with changes intended to improve and optimize battery usage. As of 8 August 2017, statistics issued by Google indicate that 29.2% of all Android devices accessing Google Play run Lollipop. Lollipop is succeeded by Marshmallow, which was released in October 2015"), 
                new Version("6.0 – 6.0.1", "Marshmallow","23","October 5, 2015", ImageSource.FromFile("Resources/drawable/marshmallow.png"), "Android \"Marshmallow\" (codenamed Android M during development) is the sixth major version of the Android operating system. First released as a beta build on May 28, 2015, it was officially released on October 5, 2015, with Nexus devices being the first to receive the update. Marshmallow primarily focuses on improving the overall user experience of its predecessor, Lollipop. It introduced a new permissions architecture, new APIs for contextual assistants (first used by a new feature \"Now on Tap\" to provide context - sensitive search results), a new power management system that reduces background activity when a device is not being physically handled, native support for fingerprint recognition and USB Type - C connectors, the ability to migrate data and applications to a microSD card, and other internal changes. As of 8 August 2017, 32.3% of devices accessing Google Play run Android 6.0."), 
                new Version("7.0 – 7.1.2", "Nougat", "24 – 25","August 22, 2016",ImageSource.FromFile("Resources/drawable/nougat.png"), "Android \"Nougat\" (codenamed Android N during development) is the seventh major version of the Android operating system. First released as an alpha test version on March 9, 2016, it was officially released on August 22, 2016, with Nexus devices being the first to receive the update. The LG V20 was the first smartphone released with Nougat. Nougat introduces notable changes to the operating system and its development platform, including the ability to display multiple apps on-screen at once in a split-screen view, support for inline replies to notifications, and an expanded \"Doze\" power - saving mode that restricts device functionality once the screen has been off for a period of time.Additionally, the platform switched to an OpenJDK - based Java environment and received support for the Vulkan graphics rendering API, and \"seamless\" system updates on supported devices. Nougat received positive reviews.The new app notification format received particular praise, while the multitasking interface was seen as a positive change, but reviewers experienced incompatible apps.Critics had mixed experiences with the Doze power-saving mode, but faster app installs and \"tweaks\" to the user interface were also reviewed positively. As of 8 August 2017, 13.5% of devices that access Google Play run Nougat, with 10.6% on Android 7.0 and 0.9% on Android 7.1."), 
                new Version("8.0 – 8.1", "Oreo", "26 – 27","August 21, 2017",ImageSource.FromFile("Resources/drawable/oreo.png"), "Android 8.0 \"Oreo\" is a version of the Android mobile operating system. It was first released as an alpha quality developer preview in March 2017 and released to the public on August 21, 2017. It contains a number of major features, including notification grouping, picture-in-picture support for video, performance improvements and battery usage optimization, and support for autofillers, Bluetooth 5, system - level integration with VoIP apps, wide color gamuts, and Wi - Fi Aware.Android Oreo also introduces two major platform features, including Android Go—a software distribution of the operating system for low - end devices, as well as support for implementing a hardware abstraction layer.")
            };
        }
    public List<Version> GetVersionsAndroid()
    {
        return _versions;
    }
}
}
